export const prompts = [
    "Majestic lion, mystical, purple, forest, HD, photography",
    "Surreal underwater world, dreamy, blue, ocean, 4K, art",
    "Enchanting castle, magical, twilight, sky, landscape, painting",
    "Glowing cityscape, futuristic, neon, skyscrapers, digital, illustration",
    "Whimsical fairytale, vibrant, green, meadow, fantasy, concept art",
    "Celestial galaxy, cosmic, stars, space, astronomical, rendering",
    "Steampunk machinery, vintage, bronze, gears, retro-futuristic, digital",
    "Exotic bird, tropical, colorful, jungle, wildlife, photograph",
    "Futuristic city, flying cars, technology, metropolis, 3D, rendering",
    "Abstract geometric patterns, vibrant, colorful, modern, digital, art",
    "Mystical forest, misty, ethereal, trees, surreal, photo manipulation",
    "Urban street art, graffiti, vibrant, culture, wall, mural",
    "Epic mountain range, snow-capped, adventure, landscape, 4K, photography",
    "Robotic companions, AI, companionship, future, sci-fi, concept art",
    "Garden of Eden, paradise, lush, flowers, serene, digital painting",
    "Vintage typewriter, retro, black and white, nostalgia, close-up, photography",
    "Cyberpunk cityscape, dystopian, futuristic, night, cybernetics, 3D, art",
    "Enigmatic ruins, ancient, mysterious, archaeological, exploration, painting",
    "Enchanted forest, fairies, magical, twilight, fantasy, digital art",
    "Abstract fluid art, vibrant, colorful, dynamic, acrylic, painting",
    "Rainbow-colored skyscape, surreal, clouds, fantasy, digital, illustration",
    "Artificial intelligence, circuitry, binary code, technology, futuristic, concept",
    "Cosmic nebula, interstellar, galaxies, space, astral, rendering",
    "Surreal desert landscape, dreamy, golden, dunes, fantasy, photo manipulation",
    "Futuristic transportation, hovercrafts, sleek, motion, sci-fi, digital painting",
    "Starry night, impressionistic, moonlit, nocturnal, van Gogh, style",
    "Magical waterfall, cascading, emerald, paradise, long exposure, photography",
    "Retro arcade, pixel art, gaming, nostalgia, neon, illustration",
    "Whale in the sky, whimsical, surreal, floating, dream, digital painting",
    "City lights, nighttime, urban, streets, long exposure, photography",
    "Abstract origami, paper folding, minimalistic, geometric, art",
    "Underwater paradise, coral reef, marine life, vibrant, underwater, photography",
    "Robotic wildlife, nature, technology, mechanical, futuristic, concept art",
    "Surreal floating islands, dreamy, ethereal, skies, fantasy, digital painting",
    "Cybernetic samurai, futuristic, warrior, hi-tech, armor, concept art",
    "Psychedelic art, trippy, colorful, abstract, mind-bending, digital",
    "Enchanted castle in the clouds, magical, floating, mist, fantasy, illustration",
    "Abstract fractal patterns, vibrant, intricate, mathematical, digital art",
    "Celestial aurora borealis, Northern Lights, night sky, ethereal, photography",
    "Ancient temples, ruins, archaeological, history, exploration, painting",
    "Fairy tale cottage, cozy, quaint, countryside, magical, digital painting",
    "Pop art explosion, vibrant, comic book, retro, collage, illustration",
    "Glowing jellyfish, bioluminescent, underwater, surreal, photography",
    "Post-apocalyptic wasteland, desolate, ruins, survival, concept art",
    "Abstract light trails, long exposure, night photography, vibrant, artistic",
    "Abstract steampunk, gears, clockwork, machinery, industrial, digital art",
    "Enchanted underwater garden, mystical, seahorses, marine flora, fantasy, illustration",
    "Futuristic cyborg, biomechanical, android, technology, sci-fi, digital painting",
    "Dreamy watercolor landscape, soft, pastel, tranquil, painting",
    "Glowing neon jungle, vibrant, futuristic, city, cyberpunk, digital, art",
  ];
  